#!/usr/bin/env bun
/**
 * Pre-Compact Hook
 *
 * Executa ANTES do /compact para preservar estado.
 * Resolve o gap de 5% de perda de contexto.
 *
 * Funções:
 * 1. Salvar estado atual da sessão
 * 2. Salvar drafts não persistidos
 * 3. Checkpoint de validações
 * 4. Atualizar progress.md
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import path from "path";

interface SessionState {
  timestamp: string;
  offer_path?: string;
  current_phase?: number;
  last_action?: string;
  pending_work?: string[];
  validations?: {
    tool: string;
    result: string;
    timestamp: string;
  }[];
}

/**
 * Get current session state from environment/context
 */
function getCurrentSessionState(): SessionState {
  const state: SessionState = {
    timestamp: new Date().toISOString(),
  };

  // Try to read from recent session state file
  const statePath = path.join(
    process.env.HOME || "~",
    ".claude/plugins/copywriting-mcp/workspace/session-state.json"
  );

  if (existsSync(statePath)) {
    try {
      const existing = JSON.parse(readFileSync(statePath, "utf-8"));
      return { ...existing, timestamp: state.timestamp };
    } catch {
      // Ignore parse errors
    }
  }

  return state;
}

/**
 * Save session state for recovery after compact
 */
function saveSessionState(state: SessionState): void {
  const workspacePath = path.join(
    process.env.HOME || "~",
    ".claude/plugins/copywriting-mcp/workspace"
  );

  if (!existsSync(workspacePath)) {
    mkdirSync(workspacePath, { recursive: true });
  }

  const statePath = path.join(workspacePath, "session-state.json");
  writeFileSync(statePath, JSON.stringify(state, null, 2));

  // Also save to history for debugging
  const historyPath = path.join(workspacePath, "session-history.jsonl");
  const historyLine = JSON.stringify({ ...state, event: "pre-compact" }) + "\n";

  try {
    const existing = existsSync(historyPath) ? readFileSync(historyPath, "utf-8") : "";
    // Keep only last 100 entries
    const lines = existing.split("\n").filter(Boolean).slice(-99);
    lines.push(historyLine.trim());
    writeFileSync(historyPath, lines.join("\n") + "\n");
  } catch {
    writeFileSync(historyPath, historyLine);
  }
}

/**
 * Update progress.md with 5-Question Reboot
 */
function updateProgressFile(state: SessionState): void {
  if (!state.offer_path) return;

  const ecosystemBase = process.env.COPYWRITING_ECOSYSTEM || path.join(process.env.HOME || "~", "copywriting-ecosystem");
  const progressPath = path.join(ecosystemBase, state.offer_path, "progress.md");

  const content = `# Progress - ${state.offer_path}

> Auto-generated by copywriting-mcp pre-compact hook
> Last updated: ${state.timestamp}

## 5-Question Reboot

1. **What was I working on?**
   ${state.last_action || "Not recorded"}

2. **What phase am I in?**
   Phase ${state.current_phase || "?"}/10

3. **What's the next step?**
   ${state.pending_work?.[0] || "Check with validate_gate"}

4. **What decisions were made?**
   ${state.validations?.map(v => `- ${v.tool}: ${v.result}`).join("\n   ") || "Check validation history"}

5. **What's blocking progress?**
   Run \`validate_gate\` to check gates status

## Quick Recovery

\`\`\`
# Load context for current phase
get_phase_context phase=${state.current_phase || 1} offer_path="${state.offer_path}"

# Check gate status
validate_gate gate_type="research" offer_path="${state.offer_path}"
\`\`\`

## Session History

| Timestamp | Action |
|-----------|--------|
| ${state.timestamp} | Pre-compact checkpoint |
${state.validations?.slice(-5).map(v => `| ${v.timestamp} | ${v.tool} |`).join("\n") || ""}

---

*This file is auto-updated. Manual edits will be overwritten.*
`;

  try {
    writeFileSync(progressPath, content);
  } catch {
    // Ignore write errors (might not have permission)
  }
}

/**
 * Main hook execution
 */
async function main() {
  try {
    console.error("[copywriting-mcp] Pre-compact: Salvando estado...");

    // Get current state
    const state = getCurrentSessionState();

    // Save state
    saveSessionState(state);

    // Update progress file if we have an offer
    if (state.offer_path) {
      updateProgressFile(state);
    }

    console.error(`[copywriting-mcp] Pre-compact: Estado salvo.
Após /compact, use get_phase_context para recuperar contexto.`);

  } catch (error) {
    console.error(`[copywriting-mcp] Pre-compact error: ${error}`);
  }
}

main();
